version: 2.1

orbs:
  node: circleci/node@5.2

workflows:
  my-workflow:
    jobs:
      - build-test-lint

jobs:
  build-test-lint:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: ./node_modules/.bin/mocha tests
      - run:
          name: Run lint
          command: npm run lint