name: "TestCI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build-test-lint
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Print Node.js version
      run: node --version
    - name: Print npm version
      run: npm --version
    - name: List global npm packages
      run: npm list -g
    - run: npm install
    - run: npm run test
    - run: npm run lint
    - name: Print environment variables
      run: printenv
